/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Bùi Xuân Sơn (https://sketchfab.com/sonbx126)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/queen-chess-c3f543f51acd40218e6fc95f17f207fa
title: Queen Chess
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/chess-q.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/chess-q.gltf')
